### ISSUE TITLE
Not working with WooCommerce 3.x

### ISSUE THREAD

**Issue by aadlung** [wirecard/woocommerce-wcp#17]
Dear Wirecard-Team,

can you please tell me when WooCommerce 3.x will be supported as I tried it with PHP5.6, PHP7.0 or PHP7.1 - and get an exception.
Using an outdated WooCommerce is not possible any more.

2017/04/20 13:13:50 [error] 24555#24555: *62115 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Call to undefined method WC_Gateway_WCP::get_id() in /mywww/wp-content/plugins/woocommerce/includes/class-wc-order.php on line 1332
PHP message: PHP Stack trace:
PHP message: PHP   1. {main}() /mywww/index.php:0
PHP message: PHP   2. require() /mywww/index.php:17
PHP message: PHP   3. require_once() /mywww/wp-blog-header.php:19
PHP message: PHP   4. do_action() /mywww/wp-includes/template-loader.php:12
PHP message: PHP   5. WP_Hook->do_action() /mywww/wp-includes/plugin.php:453
PHP message: PHP   6. WP_Hook->apply_filters() /mywww/wp-includes/class-wp-hook.php:323
PHP message: PHP   7. call_user_func_array:{/mywww/wp-includes/class-wp-hook.php:298}() /mywww/wp-includes/class-wp-hook.php:298
PHP message: PHP   8. WC_AJAX::do_wc_ajax() /mywww/wp-includes/class-wp-hook.php:298
PHP message: PHP   9. do_action() /mywww/wp-content/plugins/woocommerce/includes/class-wc-ajax.php:78
PHP message: PHP  10. WP_Hook->do_action() /mywww/wp-includes/plugin.php:453
PHP message: PHP  11. WP_Hook->apply_filters() /mywww/wp-includes/class-wp-hook.php:323
PHP message: PHP  12. call_user_func_array:{/mywww/wp-includes/class-wp-hook.php:298}() /mywww/wp-includes/class-wp-hook.php:298
PHP message: PHP  13. WC_AJAX::checkout() /mywww/wp-includes/class-wp-hook.php:298
PHP message: PHP  14. WC_Checkout->process_checkout() /mywww/wp-content/plugins/woocommerce/includes/class-wc-ajax.php:390
PHP message: PHP  15. WC_Checkout->process_order_payment() /mywww/wp-content/plugins/woocommerce/includes/class-wc-checkout.php:938
PHP message: PHP  16. WC_Gateway_WCP->process_payment() /mywww/wp-content/plugins/woocommerce/includes/class-wc-checkout.php:766
PHP message: PHP  17. WC_Order->get_checkout_payment_url() /mywww/wp-content/plugins/woocommerce-wirecard-checkout-page/class-woocommer

Regards,
Andy

**Comment by rinnhofer** [comment]
Hello,
we are currently developing a new WooCommerce plugin, but we are looking forward to check and update our Wirecard Checkout Page plugin for compatibility with WooCommerce 3.x and PHP 7.1 in the next week.

Regards,
Wirecard Plugin Team

**Comment by aadlung** [comment]
Thanks a lot for this fast answer - PHP7.1 is not that big issue as 7.0 would work too, but I cannot roll back the WooCommerce ;) Next week is perfect.

**Comment by rinnhofer** [comment]
Hello,
sorry for the delay. Our plugin is now compatible with WooCommerce 3.x and the latest WordPress version.
Unfortunatly we can't support PHP7.1 for now, but PHP7.
https://github.com/wirecard/woocommerce-wcp/tree/1.2.2

Regards,
Wirecard Plugin Team

**Comment by aadlung** [comment]
thanks a lot
