### ISSUE TITLE
Running into 500 error on payment in checkout

### ISSUE THREAD

**Issue by borisdiakur** [wirecard/woocommerce-wcp#20]
Here are the logs:

> [Fri May 12 23:59:03.285344 2017] [proxy_fcgi:error] [pid 13253] [client 95.91.217.66:27946] AH01071: Got error 'Checkout->posted was called incorrectly. Use $_POST directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->create_order, do_action('woocommerce_checkout_update_order_meta'), WP_Hook->do_action, WP_Hook->apply_filters, WC_GZD_Checkout->save_fields, WC_Checkout->__get, wc_doing_it_wrong. This message was added in version 3.0.0.\nPHP message: WC_Checkout->posted was called incorrectly. Use $_POST directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->create_order, do_action('woocommerce_checkout_update_order_meta'), WP_Hook->do_action, WP_Hook->apply_filters, WC_GZD_Checkout->save_fields, WC_Checkout->__get, wc_doing_it_wrong. This message was added in version 3.0.0.\nPHP message: PHP Fatal error:  Cannot unset $this in /var/www/vhosts/staging.mysite.com/httpdocs/wp-content/plugins/woocommerce-wirecard-checkout-page/vendor/wirecard/checkout-client-library/library/WirecardCEE/Stdlib/Client/ClientAbstract.php on line 323\n', referer: https://staging.mysite.com/checkout/

PHP version: 7.1.3
WP version: 4.7.4
WC version: 3.0.6
Theme: Storefront 2.1.8

**Comment by borisdiakur** [comment]
Downgraded PHP to 7.0.18, now getting next error:

> Response failed! Error: AUTODEPOSIT is not allowed.

Switched it off in the settings, and it works.

**Comment by jakubpolomsky** [comment]
Hello,

thank you for your input. This error message has nothing to do with the plugin, but with the config of the merchant. If you are using demo, then this really is not allowed. Try using test configuration and then you shouldn't get this message.

Regarding the compatibility with php 7.1, we will be upgrading all our plugins using the client library soon.

Have a nice day!
