### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by finea** [wirecard/woocommerce-wcp#27]
[Wirecard Woocommerce plugin errors.zip](https://github.com/wirecard/woocommerce-wcp/files/1248687/Wirecard.Woocommerce.plugin.errors.zip)
Dear Development Team,

We implemented your plugin on https://shop.addserv.de/ (and of course filled out all required Wirecard credentials) but it is not possible to make payments. Thus the plugin is deactivated for the moment on the website.
As soon as we push the buy button in the cart we get the error "SyntaxError: Unexpected token < in JSON at position 0"

We tried switching it to iFrame but then, instead of fields for filling out data appearing in an iFrame, the whole order gets confirmed and client receives a payment link in his confirmation email. This of course is not what we want, to assume some more bounces because of this supplimentary step, but even them we can't make a payment as following error appears: "Fatal error: Cannot unset $this in /html/wordpress/wp-content/plugins/woocommerce-wirecard-checkout-page/vendor/wirecard/checkout-client-library/library/WirecardCEE/Stdlib/Client/ClientAbstract.php on line 323"

We attached you 2 videos to show the 2 mentioned situations.

Please help!

Thank you,
Laszlo Erdos.

**Comment by jakubpolomsky** [comment]
Hello,

please downgrade your php version to 7.0 because 7.1 is not supported by this plugin yet.

regards

**Comment by finea** [comment]
Hello,

Thanks for the quick response! We did that and got rid of that error, but now we are facing a new one that sais "Fehler im Bestellvorgang. Versuche es bitte erneut.", meaning "Error in the order process. Please try again". And this is only appearing for the Wirecard payment methods, the other ones, we have function just right.

Thanks for your help!
BR, Laszlo

**Comment by jakubpolomsky** [comment]
Hello,

There must be a log for every error. Please post the error or journal entry to that error.

BR

**Comment by rinnhofer** [comment]
Hello @finea 

since there was no further feedback from your site I close this issue and suppose that your problems are solved.

Cheers
