### ISSUE TITLE
3 licenses

### ISSUE THREAD

**Issue by szepeviktor** [wirecard/woocommerce-wcp#45]
1. https://github.com/wirecard/woocommerce-wcp/blob/master/LICENSE with placeholders like `{description}`
1. `License: Proprietary` meta
1. "Shop System Plugins - Terms of use" comment block

Could you [concentrate on the LICENSE](https://choosealicense.com/licenses/) file?

**Comment by vitali-graz** [comment]
Hello @szepeviktor 
Thank you for the valuable input. To clarify: You can use the plugin under the GPLv2 as stated in the LICENSE file.
We will clean this up with the next major release.
Best regards,
Wirecard Shop Systems Team
